version: '2'

#
# infrastructure services
#
services:
  swarmregistrator:
    image: hypriot/rpi-registrator:master
    environment:
      - DOCKER_HOST=tcp://192.168.200.1:2378
      - constraint:node==master
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - apps
    command: -internal -cleanup -ttl 15 -ttl-refresh 5 consul://192.168.200.1:8500
  
  consultemplate:
    image: hypriot/rpi-consul-template:0.11.0
    depends_on:
      - haproxy 
    environment:
      - DOCKER_HOST=tcp://192.168.200.1:2378
      - constraint:node==master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/haproxy/:/haproxy/
    command: -consul 192.168.200.1:8500 -template "/haproxy/haproxy.ctmpl:/haproxy/haproxy.cfg:docker exec loadbalancing_haproxy_1 /haproxy-start reload"
  
  haproxy:
    image: hypriot/rpi-haproxy:1.5.8
    environment:
      - DOCKER_HOST=tcp://192.168.200.1:2378
      - constraint:node==master
    networks:
      - apps
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./haproxy/:/haproxy-override/
 
#
# two different websites to scale up
#
 
#  hypriot-website:
#    image: hypriot/rpi-busybox-httpd
#    depends_on:
#      - consultemplate 
#   networks:
#      - apps
  
  demo-hostname:
    image: firecyberice/armhf-demowebserver:hostname
    depends_on:
      - consultemplate 
    environment:
      - constraint:node!=master
    networks:
      - apps

networks:
  apps:
    driver: overlay

